version: "3"

services:
  pihole:
    image: jacklul/pihole:latest # https://github.com/jacklul/pihole-updatelists https://github.com/pi-hole/docker-pi-hole
    container_name: pihole
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - WEBPASSWORD=${WEBPASSWORD}
      - TZ=${TZ}
      - DNSSEC=true
      - PIHOLE_DNS_=9.9.9.9;1.1.1.1;2620:fe::fe;2606:4700:4700::1111
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
      - ./etc-pihole-updatelists/:/etc/pihole-updatelists/
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
